/**
 * Tamil Bible Reader - Metadata Database Map Configuration Core Data Matrix File
 * Array containing catalog configurations mapping structural definitions
 */

const bibleBooksData = [
    // Old Testament (பழைய ஏற்பாடு)
    { id: "Genesis", en: "Genesis", ta: "ஆதியாகமம்", testament: "old", chapters: 50 },
    { id: "Exodus", en: "Exodus", ta: "யாத்திராகமம்", testament: "old", chapters: 40 },
    { id: "Leviticus", en: "Leviticus", ta: "லேவியராகமம்", testament: "old", chapters: 27 },
    { id: "Numbers", en: "Numbers", ta: "எண்ணாகமம்", testament: "old", chapters: 36 },
    { id: "Deuteronomy", en: "Deuteronomy", ta: "உபாகமம்", testament: "old", chapters: 34 },
    { id: "Joshua", en: "Joshua", ta: "யோசுவா", testament: "old", chapters: 24 },
    { id: "Judges", en: "Judges", ta: "நியாயாதிபதிகள்", testament: "old", chapters: 21 },
    { id: "Ruth", en: "Ruth", ta: "ரூத்", testament: "old", chapters: 4 },
    { id: "1Samuel", en: "1 Samuel", ta: "1 சாமுவேல்", testament: "old", chapters: 31 },
    { id: "2Samuel", en: "2 Samuel", ta: "2 சாமுவேல்", testament: "old", chapters: 24 },
    { id: "1Kings", en: "1 Kings", ta: "1 இராஜாக்கள்", testament: "old", chapters: 22 },
    { id: "2Kings", en: "2 Kings", ta: "2 இராஜாக்கள்", testament: "old", chapters: 25 },
    { id: "1Chronicles", en: "1 Chronicles", ta: "1 நாளாகமம்", testament: "old", chapters: 29 },
    { id: "2Chronicles", en: "2 Chronicles", ta: "2 நாளாகமம்", testament: "old", chapters: 36 },
    { id: "Ezra", en: "Ezra", ta: "எஸ்றா", testament: "old", chapters: 10 },
    { id: "Nehemiah", en: "Nehemiah", ta: "நெகேமியா", testament: "old", chapters: 13 },
    { id: "Esther", en: "Esther", ta: "எஸ்தர்", testament: "old", chapters: 10 },
    { id: "Job", en: "Job", ta: "யோபு", testament: "old", chapters: 42 },
    { id: "Psalms", en: "Psalms", ta: "சங்கீதம்", testament: "old", chapters: 150 },
    { id: "Proverbs", en: "Proverbs", ta: "நீதிமொழிகள்", testament: "old", chapters: 31 },
    { id: "Ecclesiastes", en: "Ecclesiastes", ta: "பிரசங்கி", testament: "old", chapters: 12 },
    { id: "SongofSolomon", en: "Song of Solomon", ta: "உன்னதப்பாட்டு", testament: "old", chapters: 8 },
    { id: "Isaiah", en: "Isaiah", ta: "ஏசாயா", testament: "old", chapters: 66 },
    { id: "Jeremiah", en: "Jeremiah", ta: "எரேமியா", testament: "old", chapters: 52 },
    { id: "Lamentations", en: "Lamentations", ta: "புலம்பல்", testament: "old", chapters: 5 },
    { id: "Ezekiel", en: "Ezekiel", ta: "எசேக்கியேல்", testament: "old", chapters: 48 },
    { id: "Daniel", en: "Daniel", ta: "தானியேல்", testament: "old", chapters: 12 },
    { id: "Hosea", en: "Hosea", ta: "ஓசியா", testament: "old", chapters: 14 },
    { id: "Joel", en: "Joel", ta: "யோவேல்", testament: "old", chapters: 3 },
    { id: "Amos", en: "Amos", ta: "ஆமோஸ்", testament: "old", chapters: 9 },
    { id: "Obadiah", en: "Obadiah", ta: "ஒபதியா", testament: "old", chapters: 1 },
    { id: "Jonah", en: "Jonah", ta: "யோனா", testament: "old", chapters: 4 },
    { id: "Micah", en: "Micah", ta: "மீகா", testament: "old", chapters: 7 },
    { id: "Nahum", en: "Nahum", ta: "நாகூம்", testament: "old", chapters: 3 },
    { id: "Habakkuk", en: "Habakkuk", ta: "ஆபகூக்", testament: "old", chapters: 3 },
    { id: "Zephaniah", en: "Zephaniah", ta: "செப்பனியா", testament: "old", chapters: 3 },
    { id: "Haggai", en: "Haggai", ta: "ஆகாய்", testament: "old", chapters: 2 },
    { id: "Zechariah", en: "Zechariah", ta: "சகரியா", testament: "old", chapters: 14 },
    { id: "Malachi", en: "Malachi", ta: "மல்கியா", testament: "old", chapters: 4 },

    // New Testament (புதிய ஏற்பாடு)
    { id: "Matthew", en: "Matthew", ta: "மத்தேயு", testament: "new", chapters: 28 },
    { id: "Mark", en: "Mark", ta: "மாற்கு", testament: "new", chapters: 16 },
    { id: "Luke", en: "Luke", ta: "லூக்கா", testament: "new", chapters: 24 },
    { id: "John", en: "John", ta: "யோவான்", testament: "new", chapters: 21 },
    { id: "Acts", en: "Acts", ta: "அப்போஸ்தலர்", testament: "new", chapters: 28 },
    { id: "Romans", en: "Romans", ta: "ரோமர்", testament: "new", chapters: 16 },
    { id: "1Corinthians", en: "1 Corinthians", ta: "1 கொரிந்தியர்", testament: "new", chapters: 16 },
    { id: "2Corinthians", en: "2 Corinthians", ta: "2 கொரிந்தியர்", testament: "new", chapters: 13 },
    { id: "Galatians", en: "Galatians", ta: "கலாத்தியர்", testament: "new", chapters: 6 },
    { id: "Ephesians", en: "Ephesians", ta: "எபேசியர்", testament: "new", chapters: 6 },
    { id: "Philippians", en: "Philippians", ta: "பிலிப்பியர்", testament: "new", chapters: 4 },
    { id: "Colossians", en: "Colossians", ta: "கொலோசெயர்", testament: "new", chapters: 4 },
    { id: "1Thessalonians", en: "1 Thessalonians", ta: "1 தெசலோனிகேயர்", testament: "new", chapters: 5 },
    { id: "2Thessalonians", en: "2 Thessalonians", ta: "2 தெசலோனிகேயர்", testament: "new", chapters: 3 },
    { id: "1Timothy", en: "1 Timothy", ta: "1 தீமோத்தேயு", testament: "new", chapters: 6 },
    { id: "2Timothy", en: "2 Timothy", ta: "2 தீமோத்தேயு", testament: "new", chapters: 4 },
    { id: "Titus", en: "Titus", ta: "தீத்து", testament: "new", chapters: 3 },
    { id: "Philemon", en: "Philemon", ta: "பிலேமோன்", testament: "new", chapters: 1 },
    { id: "Hebrews", en: "Hebrews", ta: "எபிரெயர்", testament: "new", chapters: 13 },
    { id: "James", en: "James", ta: "யாக்கோபு", testament: "new", chapters: 5 },
    { id: "1Peter", en: "1 Peter", ta: "1 பேதுரு", testament: "new", chapters: 5 },
    { id: "2Peter", en: "2 Peter", ta: "2 பேதுரு", testament: "new", chapters: 3 },
    { id: "1John", en: "1 John", ta: "1 யோவான்", testament: "new", chapters: 5 },
    { id: "2John", en: "2 John", ta: "2 யோவான்", testament: "new", chapters: 1 },
    { id: "3John", en: "3 John", ta: "3 யோவான்", testament: "new", chapters: 1 },
    { id: "Jude", en: "Jude", ta: "யூதா", testament: "new", chapters: 1 },
    { id: "Revelation", en: "Revelation", ta: "வெளிப்படுத்தின விசேஷம்", testament: "new", chapters: 22 }
];

// Presets dynamic pool maps metrics rules fallback tracking arrays
const staticDailyVersesPool = [
    { book: "Psalms", bookTa: "சங்கீதம்", chapter: 23, verse: 1 },
    { book: "Matthew", bookTa: "மத்தேயு", chapter: 6, verse: 33 },
    { book: "John", bookTa: "யோவான்", chapter: 3, verse: 16 },
    { book: "Romans", bookTa: "ரோமர்", chapter: 8, verse: 28 },
    { book: "Philippians", bookTa: "பிலிப்பியர்", chapter: 4, verse: 13 },
    { book: "Isaiah", bookTa: "ஏசாயா", chapter: 41, verse: 10 },
    { book: "Proverbs", bookTa: "நீதிமொழிகள்", chapter: 3, verse: 5 },
    { book: "Psalms", bookTa: "சங்கீதம்", chapter: 46, verse: 1 },
    { book: "Galatians", bookTa: "கலாத்தியர்", chapter: 5, verse: 22 },
    { book: "Joshua", bookTa: "யோசுவா", chapter: 1, verse: 9 }
];